### ISSUE TITLE
Testing: Image Annotate module

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ImageAnnotate#1]
This module allows users to annotate images. Users may annotate media in the media context and the site page context. This includes image and non-image media that have generated thumbnails. This does not include media that have no generated thumbnails (i.e. ones using a fallback thumbnail). Users may also annotate assets in the site page context.

Test the following features:

### Media context

When editing a media, go to the "Annotate image" tab. You should see the media's image. Double-click-and-drag to create an annotation, enter a comment, and click "Ok". Save the media form. Go to the "Image annotations" tab and confirm that the annotation saved as expected. You can create as many annotations as you want.

### Site context

When configuring resource pages (via the theme interface), there are two new resource page block layouts for the item page:

- "Image annotation (all media)": allows users to add all the item's annotated media to the item page
- "Image annotation (primary media)": allows users to add the item's annotated primary media to the item page

There is one new resource page block layout for the media page:

- "Image annotations": allows users to add the annotated media to the media page

For every resource page block, make sure to view the public pages and confirm that they are rendered as expected.

### Site page context

When building a page, there are two new block layouts:

- "Image annotate media": allows users to attach an item/media to the block and annotate it
- "Image annotate asset": allows users to select an asset to the block and annotate it

On both, double-click-and-drag to create an annotation, enter a comment, and click "Ok". Save the site page form. Confirm that the annotations saved as expected. Make sure to view the public page and confirm that the annotations saved as expected.

**Comment by allanaaa** [comment]
Things seem to be mostly working. The "Image annotate asset" page block isn't displaying anything on public pages. 

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/image-annotate-test

The HTML is showing but it's just loading a blank div. This is true whether the chosen asset has an annotation or not. 

Also in the page blocks (both), when you expand the "Annotate image" dropdown, the image is overflowing the column. I realize you want the images to show at their full resolution, so maybe a pop-out window instead?

<img width="813" alt="Screenshot 2024-06-24 at 13 51 25" src="https://github.com/omeka-s-modules/ImageAnnotate/assets/28012148/da4adf70-954b-4eb1-b699-8fffecc30a26">
<img width="1134" alt="Screenshot 2024-06-24 at 13 57 01" src="https://github.com/omeka-s-modules/ImageAnnotate/assets/28012148/19845edc-7f8f-4522-90ea-12d4ec9bb9b7">

**Comment by allanaaa** [comment]
I'm not sure of your reasoning on the resource page blocks. I assume there is a technical issue here, but I wouldn't (necessarily) add a new block while we already have the Media render and Lightbox gallery blocks. 

Is there a way to if/then this? If annotations exist, show that; else, show Lightbox? I would rather annotation display be a site setting that affects existing media rendering where applicable. Or maybe the Media render block can have a public button that flips annotations on or off....

**Comment by jimsafley** [comment]
> The "Image annotate asset" page block isn't displaying anything on public pages.

It should be working now.

> Also in the page blocks (both), when you expand the "Annotate image" dropdown, the image is overflowing the column. I realize you want the images to show at their full resolution, so maybe a pop-out window instead?

It hard for me to tell. Are your images overflowing under the right sidebar? Or are they just overflowing a little on the right? I've never seen an image overflow under the sidebar. In any case, I want to avoid implementing a pop-out window if possible.

**Comment by allanaaa** [comment]
Yes, they're overflowing under the right sidebar. Sorry, it's easier to see with a longer image. 

<img width="1016" alt="Screenshot 2024-06-25 at 13 56 40" src="https://github.com/omeka-s-modules/ImageAnnotate/assets/28012148/86bcc6fe-5900-4de9-8151-54e8f0e94b39">


I am also getting overflow on public item view pages with both resource blocks - here I have both blocks in the "main with right sidebar" region and the right sidebar text is being obscured:

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item/10088

**Comment by allanaaa** [comment]
When you drop an "Image annotate media" page block in, you can't display existing annotations (ones done on the media itself)? You can only show the blank media, or new annotations created and saved only in the page block? I would do that backwards: only give annotation on the media itself, and then only represent that existing info in the page block.

**Comment by allanaaa** [comment]
The option exists to add a caption to the media you've chosen, but the captions aren't displaying on the public page. 

I think there should also be an item title with a link, the way media embed works.

**Comment by allanaaa** [comment]
Also, this might be trickier to identify and fix, but the "Image annotate media" page block is throwing the grid out of alignment. Not overflowing their columns, actually making the columns unequal across the whole page. 

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/my-grid-page

You can see the 3 html blocks in a block group are holding equal widths, while the 3 identical videos (not in a block group) are displaying at different widths. That's because the "Image annotate media" in the last row (next to 2 media embeds) is pushing its own column wide. If I remove that, the problem disappears.

**Comment by jimsafley** [comment]
> I'm not sure of your reasoning on the resource page blocks. I assume there is a technical issue here, but I wouldn't (necessarily) add a new block while we already have the Media render and Lightbox gallery blocks.

> Is there a way to if/then this? If annotations exist, show that; else, show Lightbox? I would rather annotation display be a site setting that affects existing media rendering where applicable. Or maybe the Media render block can have a public button that flips annotations on or off....

There are technical issues that may be insurmountable, but I'll look into it anyway. For one, there's no established mechanism for modules to modify the logic of an existing resource page block, at least beyond duplicating the block's code or overriding the block's partial, which are things I'll investigate.

For another, the module enables the annotation of "large" derivative images, not the original files. We do this so users can annotate files that need separate viewers to render inside a browser (e.g. PDF, TIFF). We can't just replace files in the "Media enbeds" block with their corresponding annotated images because we'd lose the file viewers. And I'm pretty sure the "Lightbox gallery" block and annotations are incompatible.

**Comment by jimsafley** [comment]
> When you drop an "Image annotate media" page block in, you can't display existing annotations (ones done on the media itself)? You can only show the blank media, or new annotations created and saved only in the page block? I would do that backwards: only give annotation on the media itself, and then only represent that existing info in the page block.

To clarify, are you suggesting that the "Image annotate media" page block should only include the annotations applied in the media context? I pretty certain that page builders will want the ability to annotate a media in context of the page, irrespective of annotations applied in the media context. What about checkbox that turns on/off the media-context annotations?

**Comment by jimsafley** [comment]
> Yes, they're overflowing under the right sidebar. Sorry, it's easier to see with a longer image.

I pushed a change that should fix the overflow.

**Comment by jimsafley** [comment]
> The option exists to add a caption to the media you've chosen, but the captions aren't displaying on the public page.

> I think there should also be an item title with a link, the way media embed works.

These are implemented now. The "Image annotate media" block now respects the attachment caption, and I've included an "Options" section where users can set a "Display title". In addition, the "Image annotate asset" block includes an "Options" section where users can add a caption.

**Comment by allanaaa** [comment]
> What about checkbox that turns on/off the media-context annotations?

Sounds fine to me.

**Comment by jimsafley** [comment]
On the "Image annotate media" block layout, I've added a "Include media annotations?" checkbox to the "Options" form. Checking the box should add media-context annotations to the public image.

**Comment by jimsafley** [comment]
I've made some changes to the resource page block layouts that should address your concerns. Site administrators can now replace the following layouts to provide annotations:

- Replace "Media embeds" with "Media embeds (with image annotations)"
- Replace "Media render" with "Media render (with image annotations)"

The replacement layouts render the media as normal, and additionally provide a "View annotations" button that toggles the annotations.

**Comment by allanaaa** [comment]
> I've made some changes to the resource page block layouts that should address your concerns. Site administrators can now replace the following layouts to provide annotations:
> 
>     * Replace "Media embeds" with "Media embeds (with image annotations)"
> 
>     * Replace "Media render" with "Media render (with image annotations)"
> 
> 
> The replacement layouts render the media as normal, and additionally provide a "View annotations" button that toggles the annotations.

I like it in theory, but the "View annotations" button isn't working. 

It will also need some bottom margin in the Media embed block, and maybe some way to indicate that it's related to the image above and not the image below:

<img width="893" alt="Screenshot 2024-07-02 at 17 17 25" src="https://github.com/omeka-s-modules/ImageAnnotate/assets/28012148/12102d5e-1c5f-4828-af05-801f1d320c26">

On the Media page, the image is centered but the button is not, so it needs positioning as well. 

<img width="1122" alt="Screenshot 2024-07-02 at 17 19 50" src="https://github.com/omeka-s-modules/ImageAnnotate/assets/28012148/e5616c8b-3260-479c-a838-0c5ec494be71">

**Comment by allanaaa** [comment]
> I like it in theory, but the "View annotations" button isn't working.

I ignored it for 24 hours, so of course it works now. 

Behaves like this on the media page - just some formatting needed: 


https://github.com/omeka-s-modules/ImageAnnotate/assets/28012148/91dcb342-1a20-4abf-a4c1-d5f6ed86943f


Item page looks fine. I would probably say "View without annotations" rather than "View media", on the button.

**Comment by allanaaa** [comment]
What are the intended user levels for the module? My Editor-level user could save an annotation; my Author-level could see the tab and create an annotation, but saving the page brought up a permission denied error. 

I would guess an Author should be able to annotate media they own, but not media they don't own? And then Reviewers and up, all permissions?

**Comment by jimsafley** [comment]
This is a bug in core. Authors should not see the "Edit media" button on resources they do not own. I've pushed the fix to core.

**Comment by allanaaa** [comment]
Just a little thing - the video itself and its annotated thumbnail are rendering at different sizes, which is moving things around on the page. I would have thought the full-size thumbnail would be the exact size as the video (looks like the video player is just an overlay). 

If I'm wrong and the thumbnail is a different size for a reason, I assume this cannot/shouldn't be helped, but I thought I'd point it out as it's a bit awkward. 


https://github.com/omeka-s-modules/ImageAnnotate/assets/28012148/7c7b44c2-8420-44c2-876b-061160f13e74

**Comment by allanaaa** [comment]
I realize assets don't generate smaller sizes, and that annotations always display at fullest size, so this interaction is happening: 

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/asset-test

I think images should always display within the width offered by the page design, even these ones. 
If not, the page block itself should have text warning people that they should resize their assets to fit "most pages" (which is unfortunately as helpful as we can be) and that overflow will be hidden, including any annotations.

**Comment by jimsafley** [comment]
> I realize assets don't generate smaller sizes, and that annotations always display at fullest size, so this interaction is happening:

I can't reproduce this, even with the same image. Every image grows and shrinks with the available space. How are you getting the second image so large?

**Comment by allanaaa** [comment]
> > I realize assets don't generate smaller sizes, and that annotations always display at fullest size, so this interaction is happening:
> 
> I can't reproduce this, even with the same image. Every image grows and shrinks with the available space. How are you getting the second image so large?

I'm getting this in Cozy, The Daily, and Center Row. All the other themes are fine. 
I did replicate it on another site with the same page setup: http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-second-site/page/asset-test

My core and all these themes are up to date, and I've deactivated as many modules as I can. That's all I know!

**Comment by jimsafley** [comment]
> just waiting on the asset-dimensions bug

@kimisgold Could you take a look at this? Explained [here](https://github.com/omeka-s-modules/ImageAnnotate/issues/1#issuecomment-2215028973) and [here](https://github.com/omeka-s-modules/ImageAnnotate/issues/1#issuecomment-2218088464), the issue is using large assets in the new "Image annotate asset" block layout. For some reason it's only happening in Cozy, The Daily, and Center Row. Otherwise, the images grow and shrink with the available space.

> and the media-replaced-with-thumbnail bit

There's not much we can do here. Media viewers often have unpredictable dimensions and can render in different sizes than the large image.

**Comment by kimisgold** [comment]
The issue was not specific to the module. Those themes didn't have a default max-width constraint on images, but it should be fixed now.

**Comment by allanaaa** [comment]
Okay, the last thing is the spacing around the "View annotations" button needs to be made consistent:

<img width="916" alt="Screenshot 2024-07-16 at 12 29 14" src="https://github.com/user-attachments/assets/e685250a-e48f-41ee-97e2-7516f045f0f9">

<img width="912" alt="Screenshot 2024-07-16 at 12 29 20" src="https://github.com/user-attachments/assets/4595689a-d9c1-4673-8d5f-cf5f81958c15">

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item/10091#lg=1&slide=0

It's not a problem in every theme, but it happens enough that I assume the module should send its own CSS to fix it? It's showing at least in The Daily, Center Row, and Thanks Roy. Also Thanks Roy has a button/text-colour issue:

<img width="403" alt="Screenshot 2024-07-16 at 12 35 46" src="https://github.com/user-attachments/assets/9fab87e4-82d5-4d79-bf2e-09090dfba634">

**Comment by jimsafley** [comment]
@kimisgold Would you please take a look at [this](https://github.com/omeka-s-modules/ImageAnnotate/issues/1#issuecomment-2231367306)?

**Comment by kimisgold** [comment]
There should be some new default styles to help with the consistency of this button layout across the themes. I also fixed the Thanks, Roy button text color issue.
